export type Grade = "A" | "B" | "C" | "D" | "E";

export const gradeMeta: Record<Grade, { word: string; color: string; note: string }> = {
  A: { word: "Great", color: "var(--color-grade-a)", note: "Purity and dose meet or beat the label." },
  B: { word: "Good", color: "var(--color-grade-b)", note: "Minor variance, still inside tolerance." },
  C: { word: "Okay", color: "var(--color-grade-c)", note: "Noticeable variance worth knowing." },
  D: { word: "Poor", color: "var(--color-grade-d)", note: "Underdosed or impure beyond tolerance." },
  E: { word: "Bad", color: "var(--color-grade-e)", note: "Fails on purity, dose, or identity." },
};

export type Compound = {
  slug: string;
  name: string;
  formal: string;
  category: string;
  summary: string;
  uses: string;
  samples: number;
  vendors: number;
  avgPurity: number;
  avgDose: number;
  lastTested: string;
  spotlight?: boolean;
};

export const categories = [
  "Metabolic",
  "Recovery",
  "Growth Secretagogue",
  "Longevity",
  "Cosmetic",
  "Sexual Health",
  "Cognitive",
] as const;

export const compounds: Compound[] = [
  {
    slug: "tirzepatide",
    name: "Tirzepatide",
    formal: "GIP and GLP 1 receptor agonist",
    category: "Metabolic",
    summary:
      "The most requested compound in the catalog and the one where vendor quality swings the widest.",
    uses: "Weight management and glucose research.",
    samples: 1184,
    vendors: 176,
    avgPurity: 98.2,
    avgDose: 96.4,
    lastTested: "26 Jun 2026",
    spotlight: true,
  },
  {
    slug: "semaglutide",
    name: "Semaglutide",
    formal: "GLP 1 receptor agonist",
    category: "Metabolic",
    summary: "High demand and high counterfeit risk, especially around stated milligram content.",
    uses: "Weight management and glucose research.",
    samples: 642,
    vendors: 57,
    avgPurity: 97.6,
    avgDose: 94.1,
    lastTested: "25 Jun 2026",
    spotlight: true,
  },
  {
    slug: "retatrutide",
    name: "Retatrutide",
    formal: "Triple receptor agonist",
    category: "Metabolic",
    summary: "Newer triple agonist where identity confirmation matters as much as purity.",
    uses: "Metabolic research.",
    samples: 731,
    vendors: 214,
    avgPurity: 98.0,
    avgDose: 95.8,
    lastTested: "26 Jun 2026",
    spotlight: true,
  },
  {
    slug: "cagrilintide",
    name: "Cagrilintide",
    formal: "Amylin analog",
    category: "Metabolic",
    summary: "Often stacked with semaglutide, so dose accuracy compounds across a protocol.",
    uses: "Appetite and metabolic research.",
    samples: 188,
    vendors: 41,
    avgPurity: 97.1,
    avgDose: 93.2,
    lastTested: "21 Jun 2026",
  },
  {
    slug: "survodutide",
    name: "Survodutide",
    formal: "GLP 1 and glucagon agonist",
    category: "Metabolic",
    summary: "Limited supply means fewer vendors and more variance per batch.",
    uses: "Metabolic research.",
    samples: 96,
    vendors: 22,
    avgPurity: 96.4,
    avgDose: 92.0,
    lastTested: "18 Jun 2026",
  },
  {
    slug: "mazdutide",
    name: "Mazdutide",
    formal: "GLP 1 and glucagon agonist",
    category: "Metabolic",
    summary: "Emerging compound with a short testing history and wide quality spread.",
    uses: "Metabolic research.",
    samples: 74,
    vendors: 18,
    avgPurity: 95.9,
    avgDose: 91.4,
    lastTested: "14 Jun 2026",
  },
  {
    slug: "bpc157",
    name: "BPC 157",
    formal: "Body protection compound 157",
    category: "Recovery",
    summary: "Healing peptide where short chain impurities are the most common failure.",
    uses: "Tissue and recovery research.",
    samples: 489,
    vendors: 88,
    avgPurity: 96.8,
    avgDose: 95.1,
    lastTested: "24 Jun 2026",
    spotlight: true,
  },
  {
    slug: "tb500",
    name: "TB 500",
    formal: "Thymosin beta 4 fragment",
    category: "Recovery",
    summary: "Frequently stacked with BPC 157 and just as prone to underfilled vials.",
    uses: "Tissue and recovery research.",
    samples: 312,
    vendors: 64,
    avgPurity: 96.2,
    avgDose: 93.7,
    lastTested: "23 Jun 2026",
  },
  {
    slug: "ghkcu",
    name: "GHK Cu",
    formal: "Copper tripeptide 1",
    category: "Cosmetic",
    summary: "Copper content and tripeptide purity both need confirming on every lot.",
    uses: "Skin and cosmetic research.",
    samples: 207,
    vendors: 49,
    avgPurity: 97.3,
    avgDose: 96.0,
    lastTested: "22 Jun 2026",
  },
  {
    slug: "cjc1295",
    name: "CJC 1295",
    formal: "Growth hormone releasing factor analog",
    category: "Growth Secretagogue",
    summary: "Often sold with or without DAC, and mislabeling between the two is common.",
    uses: "Growth hormone research.",
    samples: 264,
    vendors: 53,
    avgPurity: 95.4,
    avgDose: 91.8,
    lastTested: "24 Jun 2026",
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    formal: "Growth hormone secretagogue",
    category: "Growth Secretagogue",
    summary: "Generally clean across vendors but dose accuracy still varies by batch.",
    uses: "Growth hormone research.",
    samples: 281,
    vendors: 60,
    avgPurity: 98.1,
    avgDose: 96.6,
    lastTested: "25 Jun 2026",
  },
  {
    slug: "sermorelin",
    name: "Sermorelin",
    formal: "Growth hormone releasing hormone analog",
    category: "Growth Secretagogue",
    summary: "Stability sensitive, so handling and fill quality show up clearly in results.",
    uses: "Growth hormone research.",
    samples: 173,
    vendors: 38,
    avgPurity: 96.0,
    avgDose: 92.9,
    lastTested: "20 Jun 2026",
  },
  {
    slug: "tesamorelin",
    name: "Tesamorelin",
    formal: "Growth hormone releasing hormone analog",
    category: "Growth Secretagogue",
    summary: "Higher value compound where underdosing is the most expensive failure.",
    uses: "Growth hormone research.",
    samples: 141,
    vendors: 31,
    avgPurity: 96.7,
    avgDose: 93.4,
    lastTested: "19 Jun 2026",
  },
  {
    slug: "ghrp2",
    name: "GHRP 2",
    formal: "Growth hormone releasing peptide 2",
    category: "Growth Secretagogue",
    summary: "Classic secretagogue with a long history and reliable reference data.",
    uses: "Growth hormone research.",
    samples: 118,
    vendors: 27,
    avgPurity: 96.5,
    avgDose: 94.0,
    lastTested: "17 Jun 2026",
  },
  {
    slug: "ghrp6",
    name: "GHRP 6",
    formal: "Growth hormone releasing peptide 6",
    category: "Growth Secretagogue",
    summary: "Affordable and widely stocked, with quality that tracks vendor diligence.",
    uses: "Growth hormone research.",
    samples: 109,
    vendors: 25,
    avgPurity: 96.1,
    avgDose: 93.6,
    lastTested: "16 Jun 2026",
  },
  {
    slug: "hexarelin",
    name: "Hexarelin",
    formal: "Growth hormone secretagogue",
    category: "Growth Secretagogue",
    summary: "Potent secretagogue where small dose errors carry a larger effect.",
    uses: "Growth hormone research.",
    samples: 84,
    vendors: 19,
    avgPurity: 95.8,
    avgDose: 92.4,
    lastTested: "12 Jun 2026",
  },
  {
    slug: "motsc",
    name: "MOTS c",
    formal: "Mitochondrial derived peptide",
    category: "Longevity",
    summary: "Longevity favorite where sequence verification separates the field.",
    uses: "Metabolic and longevity research.",
    samples: 152,
    vendors: 34,
    avgPurity: 96.9,
    avgDose: 94.5,
    lastTested: "21 Jun 2026",
  },
  {
    slug: "epitalon",
    name: "Epitalon",
    formal: "Pineal tetrapeptide",
    category: "Longevity",
    summary: "Short peptide that is easy to make and easy to underfill.",
    uses: "Longevity research.",
    samples: 131,
    vendors: 29,
    avgPurity: 97.0,
    avgDose: 95.2,
    lastTested: "20 Jun 2026",
  },
  {
    slug: "nad",
    name: "NAD plus",
    formal: "Nicotinamide adenine dinucleotide",
    category: "Longevity",
    summary: "Sold in large milligram vials where fill accuracy is the headline metric.",
    uses: "Cellular and longevity research.",
    samples: 167,
    vendors: 36,
    avgPurity: 95.2,
    avgDose: 90.8,
    lastTested: "23 Jun 2026",
  },
  {
    slug: "ss31",
    name: "SS 31",
    formal: "Elamipretide",
    category: "Longevity",
    summary: "Mitochondrial peptide with a small but quality conscious vendor pool.",
    uses: "Cellular and longevity research.",
    samples: 71,
    vendors: 16,
    avgPurity: 96.3,
    avgDose: 93.0,
    lastTested: "11 Jun 2026",
  },
  {
    slug: "humanin",
    name: "Humanin",
    formal: "Mitochondrial derived peptide",
    category: "Longevity",
    summary: "Niche longevity peptide with limited but growing reference data.",
    uses: "Cellular and longevity research.",
    samples: 48,
    vendors: 12,
    avgPurity: 95.6,
    avgDose: 92.1,
    lastTested: "08 Jun 2026",
  },
  {
    slug: "melanotanii",
    name: "Melanotan II",
    formal: "Melanocortin agonist",
    category: "Cosmetic",
    summary: "Popular tanning peptide where identity and purity vary widely by source.",
    uses: "Pigmentation research.",
    samples: 196,
    vendors: 44,
    avgPurity: 96.4,
    avgDose: 93.9,
    lastTested: "22 Jun 2026",
  },
  {
    slug: "pt141",
    name: "PT 141",
    formal: "Bremelanotide",
    category: "Sexual Health",
    summary: "Melanocortin peptide where dose accuracy drives the safety margin.",
    uses: "Sexual health research.",
    samples: 158,
    vendors: 35,
    avgPurity: 97.2,
    avgDose: 94.8,
    lastTested: "21 Jun 2026",
  },
  {
    slug: "kisspeptin10",
    name: "Kisspeptin 10",
    formal: "KISS1 derived peptide",
    category: "Sexual Health",
    summary: "Hormone axis peptide where small dose errors shift outcomes quickly.",
    uses: "Endocrine research.",
    samples: 63,
    vendors: 15,
    avgPurity: 96.0,
    avgDose: 92.7,
    lastTested: "10 Jun 2026",
  },
  {
    slug: "selank",
    name: "Selank",
    formal: "Tuftsin analog",
    category: "Cognitive",
    summary: "Nasal peptide where carrier purity is as important as the active.",
    uses: "Cognitive research.",
    samples: 97,
    vendors: 22,
    avgPurity: 96.6,
    avgDose: 94.3,
    lastTested: "18 Jun 2026",
  },
  {
    slug: "semax",
    name: "Semax",
    formal: "ACTH fragment analog",
    category: "Cognitive",
    summary: "Often paired with Selank and prone to the same fill inconsistencies.",
    uses: "Cognitive research.",
    samples: 92,
    vendors: 21,
    avgPurity: 96.8,
    avgDose: 94.6,
    lastTested: "17 Jun 2026",
  },
  {
    slug: "dsip",
    name: "DSIP",
    formal: "Delta sleep inducing peptide",
    category: "Cognitive",
    summary: "Sleep peptide with a short sequence and a wide quality spread.",
    uses: "Sleep research.",
    samples: 58,
    vendors: 14,
    avgPurity: 95.5,
    avgDose: 91.9,
    lastTested: "09 Jun 2026",
  },
  {
    slug: "thymosinalpha1",
    name: "Thymosin Alpha 1",
    formal: "Immune signaling peptide",
    category: "Recovery",
    summary: "Immune peptide where purity failures show up as truncated sequences.",
    uses: "Immune research.",
    samples: 104,
    vendors: 24,
    avgPurity: 96.9,
    avgDose: 94.1,
    lastTested: "19 Jun 2026",
  },
  {
    slug: "aod9604",
    name: "AOD 9604",
    formal: "Growth hormone fragment 176 191",
    category: "Metabolic",
    summary: "Fragment peptide where mislabeling against full chain growth hormone is common.",
    uses: "Metabolic research.",
    samples: 113,
    vendors: 26,
    avgPurity: 96.1,
    avgDose: 93.3,
    lastTested: "20 Jun 2026",
  },
  {
    slug: "igf 1 lr3",
    name: "IGF 1 LR3",
    formal: "Long arginine insulin like growth factor",
    category: "Growth Secretagogue",
    summary: "Larger protein where folding and purity are difficult to get right.",
    uses: "Growth research.",
    samples: 89,
    vendors: 20,
    avgPurity: 94.8,
    avgDose: 90.5,
    lastTested: "15 Jun 2026",
  },
  {
    slug: "follistatin344",
    name: "Follistatin 344",
    formal: "Activin binding protein",
    category: "Growth Secretagogue",
    summary: "Complex protein where high purity is rare and worth confirming.",
    uses: "Muscle research.",
    samples: 47,
    vendors: 11,
    avgPurity: 93.9,
    avgDose: 89.2,
    lastTested: "07 Jun 2026",
  },
  {
    slug: "5amino1mq",
    name: "5 Amino 1MQ",
    formal: "NNMT inhibitor",
    category: "Metabolic",
    summary: "Small molecule sold alongside peptides where identity testing still matters.",
    uses: "Metabolic research.",
    samples: 66,
    vendors: 17,
    avgPurity: 97.4,
    avgDose: 95.5,
    lastTested: "16 Jun 2026",
  },
];

export function getCompound(slug: string) {
  return compounds.find((c) => c.slug === slug);
}

export function gradeFromScores(purity: number, dose: number): Grade {
  const score = purity * 0.55 + dose * 0.45;
  if (score >= 97) return "A";
  if (score >= 94.5) return "B";
  if (score >= 91.5) return "C";
  if (score >= 88) return "D";
  return "E";
}
